//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatePublishWebPage.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreatePublishWebPage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following prerequisites are required: ähnelt.
        /// </summary>
        internal static string PublishPage_BootstrapperText {
            get {
                return ResourceManager.GetString("PublishPage.BootstrapperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install ähnelt.
        /// </summary>
        internal static string PublishPage_ButtonLabel {
            get {
                return ResourceManager.GetString("PublishPage.ButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If these components are already installed, you can {launch} the application now. Otherwise, click the button below to install the prerequisites and run the application. ähnelt.
        /// </summary>
        internal static string PublishPage_BypassText {
            get {
                return ResourceManager.GetString("PublishPage.BypassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die day(s) ähnelt.
        /// </summary>
        internal static string PublishPage_Days {
            get {
                return ResourceManager.GetString("PublishPage.Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ClickOnce and .NET Framework Resources ähnelt.
        /// </summary>
        internal static string PublishPage_HelpText {
            get {
                return ResourceManager.GetString("PublishPage.HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://go.microsoft.com/fwlink/?LinkId=154571 ähnelt.
        /// </summary>
        internal static string PublishPage_HelpUrl {
            get {
                return ResourceManager.GetString("PublishPage.HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hour(s) ähnelt.
        /// </summary>
        internal static string PublishPage_Hours {
            get {
                return ResourceManager.GetString("PublishPage.Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install ähnelt.
        /// </summary>
        internal static string PublishPage_InstallButtonLabel {
            get {
                return ResourceManager.GetString("PublishPage.InstallButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string PublishPage_NameLabel {
            get {
                return ResourceManager.GetString("PublishPage.NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Publisher: ähnelt.
        /// </summary>
        internal static string PublishPage_PublisherLabel {
            get {
                return ResourceManager.GetString("PublishPage.PublisherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run ähnelt.
        /// </summary>
        internal static string PublishPage_RunButtonLabel {
            get {
                return ResourceManager.GetString("PublishPage.RunButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Customer Support ähnelt.
        /// </summary>
        internal static string PublishPage_SupportText {
            get {
                return ResourceManager.GetString("PublishPage.SupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version: ähnelt.
        /// </summary>
        internal static string PublishPage_VersionLabel {
            get {
                return ResourceManager.GetString("PublishPage.VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die week(s) ähnelt.
        /// </summary>
        internal static string PublishPage_Weeks {
            get {
                return ResourceManager.GetString("PublishPage.Weeks", resourceCulture);
            }
        }
    }
}
